apiVersion: v1
kind: Service
metadata:
  labels:
    app: menu-ui
  name: menu-ui-backend
  namespace: default
spec:
  clusterIP: 10.3.243.47
  externalTrafficPolicy: Cluster
  ports:
    - name: httpuiport
      nodePort: 32032
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: httpsuiport
      nodePort: 30630
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: menu-ui
    tier: web
  sessionAffinity: None
  type: NodePort
